### ISSUE TITLE
Maybe dont use viaTable method?

### ISSUE THREAD

**Issue by votintsev** [alexinator1/yii2-jta#2]
Hi! Nice solution. But if yii-team change viaTable method your extension can crack. Maybe create new method for attaching attributes?

**Comment by alexinator1** [comment]
well, this is extension is very wired with internal yii2 active components : ActiveQueryTrait, ActiveQuery, so once yii team decide to update them, I will have to adapt this extension as well. I chose to use viaTable method since it seems to be  logical to me, and I think it take less time to learn how to use this extension for guys who already know  how to utilize viaTable method.

**Comment by alexinator1** [comment]
![2016-04-18 00 11 40](https://cloud.githubusercontent.com/assets/1975274/14590068/64e6443e-04fa-11e6-96e6-a996a4ab3c78.png)
